### ISSUE TITLE
Complete AWS Certified Solutions Arch Associate

### ISSUE THREAD

**Issue by cujarrett** [cujarrett/personal-goals#37]
## Tasks
- [ ] - Ryan Kroonenburg's AWS Certified Solutions Arch Associate course
- [ ] - Jon Bonso's AWS Certified Solutions Architect Associate Practice Exams
- [ ] - Skillcertpro's AWS Certified Solutions Architect 2019 Practice Questions

**Comment by cujarrett** [comment]
## AWS Global Infrastructure
#### Regions

#### Availability Zones

A Data Center is a building in the country side or in the city that's filled with computer tech like servers, SANS, switches, firewalls, load balancers, storage. An Availability Zone could be one data center or several close together of data centers within a couple of miles of each other.

**Comment by cujarrett** [comment]
## Security, Identity & Compliance

#### IAM (Identity Access Management)
IAM allows you to mange users and their level of access to the AWS Console. It provides
- Centralized control of your AWS account
- Shared Access to your AWS account
- Granular Permissions
- Identity Federation (including Active Directory, FaceBook, Linkedin, etc)
- Multifactor Authentication
- Provides temporary access for users/ devices and services where necessary
- Allows you to set up your own password rotation policy
- Provides PCI DSS Compliance

#### IAM Key Terminology
1. Users - End Users such as people, employees of an organization etc.
2. Groups - A collection of users. Each user in the group will inherit the permissions of the group.
3. Policies - Policies are made up of documents called Policy documents. These documents are in a format called JSON and they give permissions as to what a User/ Role is able to do.
4. Roles - You create roles and then assign them to AWS Resources.

**Comment by cujarrett** [comment]
## Storage
#### S3 (Simple Storage Service) provides developers and IT teams with secure durable, highly scalable object storage. Amazon S3 is easy to use, with a simple web service interface to store and retrieve any amount of data from anywhere on the web.
